### ISSUE TITLE
Caching compiled code with PrecompileTools

### ISSUE THREAD

**Issue by kdpsingh** [sl-solution/InMemoryDatasets.jl#112]
I saw that DuckDB is planning to re-run their benchmarks in September: https://github.com/duckdblabs/db-benchmark/issues/23

Based on your Discourse post (https://discourse.julialang.org/t/ann-a-new-lightning-fast-package-for-data-manipulation-in-pure-julia/78197), IMD.jl appears to be very competitive with Polars when considering only the second run.

Given their plan to re-run their benchmarks in September, and the high visibility they get, just wanted to raise an issue here that it may be a good time to prioritize adding support for PrecompileTools to minimize the TTFX.

This is merely a suggestion and not a demand. Feel free to close this issue if not a priority at the moment. Thanks.

**Comment by sl-solution** [comment]
Current version of Julia (1.9.2) improves TTFX significantly and, hopefully, IMD performance shouldn't be affected too much by compilation. I expect IMD performance  be great in the case of join tasks and solving advanced questions, especially, when missing values present.

**Comment by kdpsingh** [comment]
I appreciate the reply. Feel free to close the issue. Looking forward to seeing the results on the DuckDB repo! Thanks for your work on this package!
