### ISSUE TITLE
update function not changing main dataset

### ISSUE THREAD

**Issue by evensong** [sl-solution/InMemoryDatasets.jl#114]
I'm working with a utility company to consolidate their data (it's kind of a mess). Because of how things are set up right now, I have one dataset of account numbers, one of geospatial data, and one into which I'm trying to merge stuff; that third dataset needs to be updated with data from the others and then exported to the server.

The update function looks perfect for this, but when I feed in my data, nothing has been updated. If I use the update function, it returns the same dataset, and if I use update!, nothing seems to be changed. My call to the update function looks like this:

test2 = update(Dataset(main_data), Dataset(geo_data[!, [:referenceId, :poleNumber]]), on = :referenceId, mode = :all)

I will most likely be updating more columns, but this is what I'm starting with. Am I making a bad call to the function, or is there some bug?

 I can provide more details of the datasets if needed (I just have to be careful not to  include anything sensitive).

Thanks in advance!

**Comment by sl-solution** [comment]
If you can share a simple example, it would be helpful.  Anyway, you may check the followings:

* :referenceid is available in both datasets
* :referenceid in two datasets are comparable
* the column names that you like to update are identical in both data sets and have the same data type

**Comment by evensong** [comment]
It looks like the main dataset got its data type garbled into a weird chain vector at some point, so that may be the issue. I'll clean it up and close if that fixes it.

**Comment by sl-solution** [comment]
> It looks like the main dataset got its data type garbled into a weird chain vector at some point, so that may be the issue. I'll clean it up and close if that fixes it.

Probably, you used CSV.jl to read data into Julia.

PS: both chained vector and String vector affect performance, if the performance is critical to you, you may need to think about fixed length string or PooledArrays.

**Comment by evensong** [comment]
Yup, that was it. Thanks for helping me narrow that down! The performance shouldn't be an issue for this particular case.
