### ISSUE TITLE
remove type piracy of `convert(Any, x)`

### ISSUE THREAD

**Issue by simeonschaub** [sl-solution/InMemoryDatasets.jl#38]
`convert(Any, x)` should always be a noop, but it seems like this package intentionally overloads it with a different meaning:

https://github.com/sl-solution/InMemoryDatasets.jl/blob/049d64ad92d8b6ee67c2a33b94c3b34d5919526d/src/abstractdataset/dscol.jl#L28

This will likely cause issues once https://github.com/JuliaLang/julia/pull/43671 is merged, so this should be removed or a different function should be used for this instead.

**Comment by sl-solution** [comment]
This is not really a new meaning just is passing the conversion operation to one of the field inside the `SubOrDSCol` structure.
Anyway, what we should do about type ambiguity caused by `Base.convert(::Type{Any}, x) `

**Comment by simeonschaub** [comment]
> This is not really a new meaning just is passing the conversion operation to one of the field inside the SubOrDSCol structure.

Yes, but `convert(Any, x)` should not unwrap anything.

> Anyway, what we should do about type ambiguity caused by `Base.convert(::Type{Any}, x)`

That method should just return `x`. You might want to remove these overloads for `convert` here altogether to avoid excessive invalidatioms this causes and move this functionality to a function with a different name. That `convert(<:SubOrDSCol, x::SubOrDSCol)` doesn't just return `x` either is probably an issue as well, since that won't play nicely if used together with return type annotations for example.

**Comment by sl-solution** [comment]
does defining `Base.convert(T::Type{AbstractVector}, col1::SubOrDSCol)`ok?

**Comment by simeonschaub** [comment]
Yes, that should be fine and avoid most of the invalidations.

**Comment by simeonschaub** [comment]
(You probably meant `Type{<:Abstract vector}` though)

**Comment by sl-solution** [comment]
oops, fixed it
