### ISSUE TITLE
what's the relation of  InMemoryDatasets.jl, DataSets.jl and DataFrames.jl ??

### ISSUE THREAD

**Issue by zsz00** [sl-solution/InMemoryDatasets.jl#40]
what's the relation of  InMemoryDatasets.jl, [
DataSets.jl](https://github.com/JuliaComputing/DataSets.jl) and DataFrames.jl ??

**Comment by sl-solution** [comment]
`InMemoryDatasets.jl` is for working with tabular data in `Julia`, so in this respect is similar to `DataFrames.jl`.  Its constructors are similar  to `DataFrames.jl` and its syntax is familiar with `DataFrames.jl` users (with some differences, e.g. see `unique` or `filter` ). However, for computations `InMemoryDatasets.jl` uses innovative algorithms which make `InMemoryDatasets.jl` efficient and feature rich.

There is no connection with `DataSets.jl` just a similar name.
