### ISSUE TITLE
byrow problem (no multithreading?)

### ISSUE THREAD

**Issue by minhuangr** [sl-solution/InMemoryDatasets.jl#42]
I have tried the example below on Win10 and Unbuntu 18 under WSL2 with Julia 1.7.1. Results are similar.

julia> Threads.nthreads()
8

julia> using InMemoryDatasets, BenchmarkTools

julia> ds = Dataset(rand(10^5, 100), :auto);

julia> m = Matrix(ds);

julia> @btime byrow(ds, sum, 1:100);
22.097 ms (171 allocations: 889.34 KiB)

julia> @btime sum(m, dims = 2);
15.696 ms (6 allocations: 879.06 KiB)

julia> @btime byrow(ds, sum, 1:100, threads = true);
22.181 ms (168 allocations: 889.17 KiB)

**Comment by sl-solution** [comment]
Based on allocations, it seems that no parallel computation is happening. Would you please run the following code and share the timing for n=8?

```julia
julia> function f1(n)
           for i in 1:n
               sleep(1)
           end
       end
f1 (generic function with 1 method)

julia> function f2(n)
           Threads.@threads for i in 1:n
               sleep(1)
           end
       end
f2 (generic function with 1 method)
```

**Comment by minhuangr** [comment]
It seems to be fine for this.

julia> @btime f2(8)
  1.007 s (81 allocations: 5.98 KiB)

julia> @btime f1(8)
  8.072 s (40 allocations: 1.12 KiB)

**Comment by sl-solution** [comment]
> It seems to be fine for this.
> 
> julia> @Btime f2(8) 1.007 s (81 allocations: 5.98 KiB)
> 
> julia> @Btime f1(8) 8.072 s (40 allocations: 1.12 KiB)

Is `IMD` loaded when you were benchmarking? If not, would you please load and rerun?

**Comment by minhuangr** [comment]
```julia
julia> Threads.nthreads()
8

julia> using InMemoryDatasets, BenchmarkTools

julia> ds = Dataset(rand(10^5, 100), :auto);

julia> m = Matrix(ds);

julia> @btime byrow(ds, sum, 1:100);
  22.274 ms (171 allocations: 889.34 KiB)

julia> @btime sum(m, dims = 2);
  15.808 ms (6 allocations: 879.06 KiB)

julia>

julia> function f1(n)
           for i in 1:n
               sleep(1)
           end
       end
f1 (generic function with 1 method)

julia>

julia> function f2(n)
           Threads.@threads for i in 1:n
               sleep(1)
           end
       end
f2 (generic function with 1 method)

julia>

julia> @btime f2(8)
  1.004 s (81 allocations: 5.98 KiB)

julia> @btime f1(8)
  8.063 s (40 allocations: 1.12 KiB)

julia> Threads.nthreads()
8
```

**Comment by sl-solution** [comment]
The last thing you should check is the value of `IMD.__NCORES`, since the `byrow` behind the scene uses `Threads.@threads` and as you checked there is no problem with `Threads.@threads` in your system. 

One thing you may check to be sure that`@btime byrow(ds, sum, 1:100);` is not parallelised is by looking at system monitor.

**Comment by minhuangr** [comment]
I have used htop to find that there is only one process working there.

Yep, IMD.__NCORES is 1. Is there a way to fix it?

**Comment by sl-solution** [comment]
It is defined in the following address:

https://github.com/sl-solution/InMemoryDatasets.jl/blob/209c72ec58d6c9838b1fd4b80ef5ac067064422e/src/byrow/row_functions.jl#L19

As you can see it is simply equals to `Threads.@nthreads()` - So if `Threads.@nthreads()` shows 8 in your session it also should be set to 8 in `IMD`, unless you run a code which doesn't allow `IMD` to set it as 8.

**Comment by minhuangr** [comment]
Emm, this is quite strange. I activate a new environment and only install InMemoryDatasets but IMD.__NCORES is still 1 though Threads.nthreads() is 8.

**Comment by sl-solution** [comment]
I created a `debug` branch, which I replaced every occurrence of `__NCORES` with `Threads.nthreads()`. You may check this branch and see if every thing is ok?

**Comment by minhuangr** [comment]
Maybe you need to modify byrow.jl as well.

**Comment by minhuangr** [comment]
I have replaced __NCORES in byrow.jl and now everthing works.

**Comment by sl-solution** [comment]
Great!

So this is a bug. I will fix it

**Comment by sl-solution** [comment]
checkout master it is fix, thanks.

**Comment by minhuangr** [comment]
Yep. The master version works. Thanks.
