### ISSUE TITLE
Add DataFrames.jl copyright line to LICENSE.md

### ISSUE THREAD

**Issue by nalimilan** [sl-solution/InMemoryDatasets.jl#45]
I saw that you mention on README.md that the work done in DataFrames.jl has helped developing this package. Thanks for putting that acknowledgement there! I just wanted to note that since the code is derived from the DataFrames.jl codebase, the MIT license requires that LICENSE.md include [the copyright line from DataFrames.jl](https://raw.githubusercontent.com/JuliaData/DataFrames.jl/d4e50a570dba8e7077ea3cd4c96247019dc2e179/LICENSE.md), i.e. "Copyright (c) 2012-2022: Harlan Harris, EPRI (Tom Short's code), Chris DuBois, John Myles White, Milan Bouchet-Valat, Bogumił Kamiński and other DataFrames.jl contributors."

**Comment by sl-solution** [comment]
Thanks for bringing up this issue. Probably I should think about it a little more since I think probably we need to add some other MIT copyright stuffs too, e.g. creating dictionary is based on `Julia` Base, etc.
