### ISSUE TITLE
Grouping by Integers

### ISSUE THREAD

**Issue by GregorMatheis** [sl-solution/InMemoryDatasets.jl#49]
First of all I really like the idea of the package! I came across a very strange behaviour when using groupby().
If I group by two columns one an integer and the other a string with only one unique value, the aggregation result using combine() can different depending on the order of the columns in the groupby().

Some code examples:

Group by columns: integer and string with only one unique value:
```
ds = Dataset(key = repeat(["key1"], 10), day = repeat(collect((today() - Day(4)) : Day(1): today()), 2), value = 1:10)

combine(groupby(ds, [:day, :key]), :value => mean => :daily_avg)  # correct
combine(groupby(ds, [:key, :day]), :value => mean => :daily_avg)  # wrong
```
The second one doesn’t show the correct result while the first one is fine.

Grouping by columns: character and string with only one unique value:
```
ds = Dataset(key = repeat(["key1"], 10), day = repeat('a':'e', 2), value = 1:10)

combine(groupby(ds, [:day, :key]), :value => mean => :daily_avg)  # correct
combine(groupby(ds, [:key, :day]), :value => mean => :daily_avg)  # correct
```
Both versions give the same correct result.

Grouping by columnes: Integer and string with more then one unique value:
```
ds = Dataset(key = repeat(["key1", "key2"], inner = 10), day = repeat(1:5, 4), value = 1:20)

combine(groupby(ds, [:day, :key]), :value => mean => :daily_avg)  # correct
combine(groupby(ds, [:key, :day]), :value => mean => :daily_avg)  # correct
```
Both versions correct and with expected sorting of result depending on order of columns in group by.

I'm using:

> Julia Version 1.7.0
> Commit 3bf9d17731 (2021-11-30 12:12 UTC)
> Platform Info:
>   OS: macOS (arm64-apple-darwin21.1.0)
>   CPU: Apple M1
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
> Environment:
>   JULIA_EDITOR = code

InMemoryDatasets v0.6.10

**Comment by sl-solution** [comment]
Thanks for reporting, I know where is the bug. I will fix it soon.
