### ISSUE TITLE
Missings

### ISSUE THREAD

**Issue by matthieugomez** [sl-solution/InMemoryDatasets.jl#54]
I agree with you that missings are not easy to deal with in Julia.  Did you play with the idea of defining specialized versions of mean/sum on DatasetColumn that would skip missing? This would be a way to avoid type piracy without introducing new functions such as IMD.mean

**Comment by sl-solution** [comment]
The `DatasetColumn` type is only defined for making sure that users don't use columns of a data set out of context (if such a requirement is needed a copy of columns must be used), and in general, `IMD` computations are done on abstract `Vectors`. 
I decided to go with defining private functions for common operations (while handling missing values efficiently). The only inconvenience with this would be users must call them using the pattern `IMD.fun`. The package manual documents those functions in more details.
