### ISSUE TITLE
Add option to print a dataset without the lines format and type

### ISSUE THREAD

**Issue by ufechner7** [sl-solution/InMemoryDatasets.jl#65]
While often it is important to know the format and the type, probably the end user does not want to see it.

Furthermore these rows make it difficult to display narrow columns without much white space.

I want to be able to print columns that contain one byte of data each in this format:
```
B1 B2 B3 B5
01 0a 1f 33 
```

**Comment by ufechner7** [comment]
The option actually exists:
```
show(ds, eltypes=false)
```
Just the documentation is missing...

**Comment by sl-solution** [comment]
`?show` now states that `eltype=false` drop column types and formats.
