### ISSUE TITLE
Add option to print a dataset without row number

### ISSUE THREAD

**Issue by ufechner7** [sl-solution/InMemoryDatasets.jl#66]
The first column in my datasets is the time in seconds. So normally do not need the row number. Would be nice if I could print a dataset without the column "Row".

**Comment by sl-solution** [comment]
You may pass the `show_row_number = false` keyword argument, e.g.
```
julia> show(ds, show_row_number = false)
```

Showing `Datasets` uses the `PrettyTables` package, thus, any option supported by that package will be usable in `show(ds)`.

**Comment by ufechner7** [comment]
Great! Good to know. Would be good if this info would appear in the documentation of this package.

**Comment by sl-solution** [comment]
The `PrettyTables` package has many keyword arguments, I put a note in the help of `show` in `IMD` to refer users to `PrettyTables.jl` (you may see it as the last option in docstring of `show`).

**Comment by ufechner7** [comment]
Works.
