### ISSUE TITLE
Improve documentation of filter()

### ISSUE THREAD

**Issue by ufechner7** [sl-solution/InMemoryDatasets.jl#69]
The documentation of the filter function is missing an example how to filter a dataset depending on the content of one column that might contain missing values. Here is an example:

```julia
using InMemoryDatasets
# create a demo data set of CAN bus messages and filter the result

function demo_data()
    n = 100000
    m = 8
    time = 0.1:0.1:n*0.1
    addr = rand(Int16(0x101):Int16(0x12e), n)
    columns = (Symbol("d", i) => rand(UInt8, n) for i in 1:m)
    ds = Dataset(;time, addr, columns...)
    ds.addr[5] = missing
    ds
end
ds = demo_data()

# CAN bus devices with a given set of addresses are input devices
function isinput(addr)
    if ismissing(addr) return false end
    addr in [0x103, 0x106, 0x109]
end

# create the dataset msg_in with all messages from input devices
msg_in = filter(ds, :addr, by=isinput)
```

I took me weeks to figure this out. The examples in the documentation don't cover this use case and the syntax of DataFrames does not work either.

With DataFrames the syntax would be:
```julia
filter(:addr => isinput, ds)
```
Very different. Was there a reason to choose a different syntax?

At least it would be nice to have a page or paragraph in the documentation:
"notable differences to DataFrames"

**Comment by giantmoa** [comment]
I think for the example you've posted `semijoin` is the right function,
```julia
semijoin(ds, Dataset(addr=[0x103, 0x106, 0x109]), on = :addr)
```

**Comment by sl-solution** [comment]
As @giantmoa  mentioned try to use `contains`'s family of functions. However, I guess adding extra examples would be good. If you like to open PR, please go for it, otherwise, I can add an example about this.

Probably we should add a feature to `filter` to deal with `missing` directly, for example, user can call `filter(ds, :, missings = false)` to drop rows which return `missing`, we have similar option in `mask`.

> Was there a reason to choose a different syntax?

We like the first argument of all functions in `IMD` be the data set itself, moreover, `filter` is just a wrap around `byrow`.

> At least it would be nice to have a page or paragraph in the documentation:
> "notable differences to DataFrames"

I think it is a good idea not to refer to any other data manipulation tool, since there are many of them and I do not like to leave any of them out. Additionally, almost every function in `IMD` is different from its counterpart in `DataFrames` even the functions which user may assume are the same , e.g. see the docstrings of functions like `unique`, `flatten` (`flatten!`), `repeat` (`repeat!`), `leftjoin` (`leftjoin!`), `innerjoin`, etc. Thus, it is not practical to mention all of them.

**Comment by ufechner7** [comment]
I simplified the example.

**Comment by ufechner7** [comment]
> I think for the example you've posted `semijoin` is the right function,
> 
> ```julia
> semijoin(ds, Dataset(addr=[0x103, 0x106, 0x109]), on = :addr)
> ```

Well, for an data analyst that might be straight forward, but for an average electrical engineer that is too much of abstraction.

**Comment by ufechner7** [comment]
> Probably we should add a feature to `filter` to deal with `missing` directly, for example, user can call `filter(ds, :, missings = false)` to drop rows which return `missing`, we have similar option in `mask`.

That would be nice!

**Comment by sl-solution** [comment]
check the master branch. I have added a new keyword argument to `filter/!`, `delete/!` which can help to resolve this issue. Regarding your question, you can call
```
msg_in = filter(ds, :addr, by=in([0x103, 0x106, 0x109]), missings = false)
```

**Comment by ufechner7** [comment]
Why can the keywords type and by used alternatively?

**Comment by giantmoa** [comment]
AFAIU, you are filtering on a single column, you can call either `byrow(ds, all, :addr, by=in([0x103, 0x106, 0x109]))` or `byrow(ds, in([0x103, 0x106, 0x109]), :addr)`.

**Comment by ufechner7** [comment]
Thanks for pointing out that I can also use byrow directly, but the topic here is the documentation of the filter function. Is there a list of keyword arguments and their meaning for the function filter() anywhere available? If not it should be added to the docstring.

**Comment by sl-solution** [comment]
> AFAIU, you are filtering on a single column, you can call either `byrow(ds, all, :addr, by=in([0x103, 0x106, 0x109]))` or `byrow(ds, in([0x103, 0x106, 0x109]), :addr)`.

correct.

> Thanks for pointing out that I can also use byrow directly, but the topic here is the documentation of the filter function. Is there a list of keyword arguments and their meaning for the function filter() anywhere available? If not it should be added to the docstring.

Basically, `type` and (recently) `missings` are the only keyword arguments, and by default, `type = all` and `missings = missing`, other keywords depends on the value of `type`. This is mentioned in docstring of `filter`, `filter!`, `delete`, and `delete!` and the package documentation at [filtering](https://sl-solution.github.io/InMemoryDatasets.jl/stable/man/filter/#byrow).

Do you think we should add extra text about this in docstrings?

**Comment by ufechner7** [comment]
> Basically, `type` and (recently) `missings` are the only keyword arguments

Well, that cannot be true. `by` is also a keyword argument, or am I wrong?

**Comment by ufechner7** [comment]
Current docstring says:
```
  filter(ds::AbstractDataset, cols; [type = all,...])
  A convenient shortcut for ds[byrow(ds, type, cols; ...), :].

  type can be any function supported by byrow which returns a Vector{Bool} or BitVector.
  See byrow, filter!, delete!, delete
```
Missing:
1. an explanation of by=
2. and if this example would be valid
`filter(ds, :addr, type=in([0x103, 0x106, 0x109]))`
then the explanation of the type parameter would be wrong, because the function `in` is NOT returning a Vector{Bool}, but just a `Bool`

**Comment by sl-solution** [comment]
I see,

> Well, that cannot be true. `by` is also a keyword argument, or am I wrong?

You are right - well, half-right! 
* you are right about the wording of the docstring, it might be better to say "type can be any function supported by `byrow` which **byrow of the function** returns a Vector{Bool} or BitVector."
* however, `by` is not a keyword argument of `filter`. Since `byrow` of `all` (the default value for `type`) has `by`in its keyword argument, user can pass it to `filter`.

Do you think this clarifies the issue?

**Comment by ufechner7** [comment]
Please, do NOT refer to byrow in the docstring of filter! This is very bad style. You cannot expect people who want to use the filter function to know or understand the byrow function. If I can use by as keyword argument of filter it IS a keyword argument of filter. Everything else is just confusing and stops people to use this library.

**Comment by sl-solution** [comment]
But, something like `filter(ds, :)` is just `ds[byrow(ds, all, :), :]`. Thus it is basically `byrow` not `filter`.

**Comment by ufechner7** [comment]
> But, something like `filter(ds, :)` is just `ds[byrow(ds, all, :), :]`. Thus it is basically `byrow` not `filter`.

That is an implementation detail. The user of the filter function is NOT interested in this implementation detail.

**Comment by sl-solution** [comment]
probably we can enrich the docstring of `filter` by adding more details about `type = all` and `type = any` (two special cases where most of the use cases should fall in)?

**Comment by ufechner7** [comment]
> probably we can enrich the docstring of `filter` by adding more details about `type = all` and `type = any` (two special cases where most of the use cases should fall in)?

That would already be very helpful...

**Comment by ufechner7** [comment]
Created a blog post: https://ufechner7.github.io/2022/08/12/filtering-and-browsing-datasets.html

Of course I can update it when a new version of InMemoryDatasets is released...
